### ISSUE TITLE
Adding Root Certificates to trust the Certificate of a Downstream FHIR Server

### ISSUE THREAD

**Issue by chrmey** [miracum/fhir-gateway#6]
Is there an environment variable or a path mapping that i can use to add a root Certificate of my CA into the FHIR Gateway? This is needed so the FHIR Gateway trusts the certificate of my downstream FHIR-Server.

**Comment by chrmey** [comment]
Also a possibility for using Basic-Auth would be very useful.

**Comment by chrmey** [comment]
Workaraound: Mouting a custom Truststore as JKS File into the container. Passing it to the JVM with the JAVA_TOOL_OPTIONS:
-Djavax.net.ssl.trustStore=/path/to/certs -Djavax.net.ssl.trustStorePassword=truststorepasswd 

However, now the correct certificate path can be build, but the hostname validation fails. It seems possible, that this occurs because there is no SAN given in the certificate. Although the hostname is equal to the CN in the certificate.

**Comment by chgl** [comment]
That seems possible since the CN field is deprecated nowadays: https://frasertweedale.github.io/blog-redhat/posts/2017-07-11-cn-deprecation.html https://unmitigatedrisk.com/?p=381
